### ISSUE TITLE
移动端设置属性

### ISSUE THREAD

**Issue by banjuer** [ohmstance/trilium-lightpad-theme#1]
非常棒的主题，移动端使用体验得到了极大的提升，不过有个问题想咨询下，在移动端怎么设置笔记的属性呢？摸索了半天，没有试出来 😄

**Comment by ohmstance** [comment]
Sorry, I don't know Chinese, so I'm putting what you typed through Google Translate.

Right now it isn't possible to change note properties from the mobile frontend. This would require changes on Trilium side, or perhaps a custom js script to add back this feature. You could only change note properties through the desktop frontend.

There are features not available in the mobile frontend but is exposed, such as the full search menu. Admittedly, the mobile frontend is a bit limited in features.

**Comment by banjuer** [comment]
> Sorry, I don't know Chinese, so I'm putting what you typed through Google Translate.
> 
> Right now it isn't possible to change note properties from the mobile frontend. This would require changes on Trilium side, or perhaps a custom js script to add back this feature. You could only change note properties through the desktop frontend.
> 
> There are features not available in the mobile frontend but is exposed, such as the full search menu. Admittedly, the mobile frontend is a bit limited in features.

thanks,I found another way, set attribute promoted, then the value of the property can then be maintained on mobile
