### ISSUE TITLE
Install inop

### ISSUE THREAD

**Issue by doobes** [ohmstance/trilium-lightpad-theme#3]
Went through the procedure. Doesn't show up in themes list.

None of the imported notes have any imported attributes.

Both .js files replete with code errors

**Comment by doobes** [comment]
**I added "#appTheme=Lightpad " as an Owned Attribute to Lightpad.css, and it appeared in the theme selection.

Both js files displaying multiple errors.**

**Comment by ohmstance** [comment]
Weird. Just to verify, you are importing the theme zip file in the releases page, right? https://github.com/ohmstance/trilium-lightpad-theme/releases/tag/v20240330

Each note should have the following attribute:
- Lightpad: `#iconClass="bx bx-expand-horizontal" #appTheme=Lightpad`
- desktop.js: `#run=frontendStartup`
- mobileOpt.js: `#appCssrun=mobileStartup`
- Inter.woff2: `#originalFileName=Inter.woff2 #customResourceProvider="themes/Lightpad/Inter.woff2"`
- apple-touch-icon.png: `#originalFileName=apple-touch-icon.png #customResourceProvider="themes/Lightpad/apple-touch-icon.png"`

Is this a Trilium server instance? What browser are you using Trilium with?

**Comment by doobes** [comment]
Ok,

No, I had downloaded using the code button. I had to search the page to find the "Releases" selection over on the right hand side. Yours is one of the few themes that make us of that.

I've got a server install, a Windows native install and a Linux native install.

I access the server install from Android devices (A Pixel 3A XL phone, and a Samsung Galaxy Tab 4 tablet) using Firefox (for now at least. Firefox has a battery consumption issue at present, and if it doesn't get resolved soon, I'll switch to another browser).

My phone and tablet don't demonstrate js code errors.  Everything else does:

Linux native

![Trilium Linux LaunchPad](https://github.com/ohmstance/trilium-lightpad-theme/assets/23409761/54715de5-22ca-44ec-b681-e8c9c277c03b)

Linux Firefox

![Trilium Linux LaunchPad Firefox](https://github.com/ohmstance/trilium-lightpad-theme/assets/23409761/dd2d38e9-5332-42e2-9dc3-8b9e4a687561)

Windows native

![Trilium Windows LaunchPad](https://github.com/ohmstance/trilium-lightpad-theme/assets/23409761/101ed392-23a9-4b25-bda5-781bb6ba40c6)

My phone version will close Firefox after about 90 seconds. Tablet version doesn't exhibit this.

Thanks for responding.

**Comment by ohmstance** [comment]
That is to be expected as Trilium uses ESLint 5 for code linting which by default parses JS ES5 syntax. The `let` declaration is introduced with ES6 (2015). Oh and I don’t think the mobile frontend supports code linting, hence the absence of error.

ESLint can lint newer ECMAScript syntax but that requires a change to Trilium's ESLint config [here](https://github.com/zadam/trilium/blob/master/libraries/codemirror/addon/lint/eslint.js#L49) to `ecmaVersion: 2019` (latest supported by ESLint 5.11.1).

Just ignore the error.
